version: "3"

services:
  app:
    build: .
    container_name: fastapi-app
#    command: bash -c "uvicorn fastapi_app.main:app"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
