
name: My-tests-fast-api

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ubuntu download
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checout@v2

      - name: run-ls
        run: ls -la

      - name: run-tests
        run: ./tests/test_api.py
