
name: My-tests-fast-api

on:
  push:
    branches:
      - main

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - user: actions/checout@v2

      - name: run-ls
        run: ls -lah

      - name: run-tests
        run: ./tests/test_api.py
