
name: My-tests-fast-api

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v2
        with:
          poetry_version: "1.2.2"
      - name: run-ls
        run: ls -la
      - name: prep-app
        run: |
          poetry update package
          uvicorn fastapi_app.main:app --reload
          cd tests
          ls -la
          python test_api.py

  app:
    name: FastApi
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run app
        run: |
          ls -la
      - name: run-tests
        run: |
          cd tests
          ls -la
          python test_api.py
